### ISSUE TITLE
get 'kvsDgIntegratorLoadBalancer' error when running Cloudformation stack

### ISSUE THREAD

**Issue by tempops** [deepgram/amazon-connect-integration#5]
Hello, 

I followed all of the steps but get an error which stops all processes in the cloud formation.

The error starts at this step: kvsDgIntegratorLoadBalancer with a CREATE_FAILED error.

Please help me solve this, is the issue doe to Load Balancer specific configs?

**Comment by RyanChimienti** [comment]
Hey @tempops , is there any more information in the CloudFormation console about what caused the CREATE_FAILED? A more specific error message would help.

In my experience, the most common cause of creation failures is lacking the necessary IAM permissions. The easiest way to avoid these would be to have an admin on the AWS account run the CloudFormation script.
